---
title: "Text Mining News Articles"
author: "Laura Banaszewski, Mary Kate Carara, and Lauren Gamber"
date: "2026-10-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Load Packages
library(tidyverse)
library(lubridate)
```


```{r, eval = FALSE}
csv_file <- "all-the-news-2-1.csv"  
 
pattern <- regex(
  "self[- ]driving|driverless|autonomous (car|vehicle|truck|driving)|robo[- ]?taxi|waymo|tesla'?s? autopilot",
  ignore_case = TRUE) # AI-generated code: Uses a regex pattern to identify text related to self-driving cars 


keep_self_driving <- function(chunk, pos) {
   # filters inserted text to contain the defined regex pattern in title or article
  chunk %>% filter(str_detect(title, pattern) | str_detect(article, pattern))
}

subset_allnews <- read_csv_chunked(
  csv_file,
  DataFrameCallback$new(keep_self_driving),
  chunk_size = 100000,
  col_types = cols(.default = "c")  # make every column default to a character type
)
 

subset_allnews_clean <- subset_allnews %>%
  mutate(
    date        = as_date(substr(date, 1, 10)),          # "YEAR-MONTH-DAY 00:00:00" date
    title_match = str_detect(title, pattern),            # TRUE if the title mentions the topic
    body_hits   = str_count(article, pattern),           # how many times the article mentions the pattern
    word_count  = str_count(article, "\\S+")             # rough article length not including white space
  ) %>%
  filter(title_match | body_hits >= 3) %>%               
  filter(word_count >= 150) %>%               
  distinct(title, .keep_all = TRUE)                      # remove duplicate articles

 
nrow(subset_allnews_clean)
count(subset_allnews_clean, publication, sort = TRUE)
#write_csv(subset_allnews_clean, "self_driving_articles.csv")
```


```{r}
self_driving <- read_csv("self_driving_articles.csv")
```




